# Generated by Django 4.2.7 on 2023-11-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("a_id", models.IntegerField(primary_key=True, serialize=False)),
                ("a_name", models.CharField(max_length=50)),
                ("remaining", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="AccountBook",
            fields=[
                ("ab_id", models.IntegerField(primary_key=True, serialize=False)),
                ("ab_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("b_id", models.IntegerField(primary_key=True, serialize=False)),
                ("b_amount", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                ("l_id", models.IntegerField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField()),
                ("l_amount", models.FloatField()),
                ("remark", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "type_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("is_out", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("u_id", models.IntegerField(primary_key=True, serialize=False)),
                ("u_name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "a_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.account"
                    ),
                ),
                (
                    "u_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
            options={"unique_together": {("u_id", "a_id")},},
        ),
        migrations.CreateModel(
            name="UserAB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ab_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.accountbook",
                    ),
                ),
                (
                    "u_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
            options={"unique_together": {("u_id", "ab_id")},},
        ),
        migrations.CreateModel(
            name="LogType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "l_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.log"
                    ),
                ),
                (
                    "type_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.type"
                    ),
                ),
            ],
            options={"unique_together": {("l_id", "type_name")},},
        ),
        migrations.CreateModel(
            name="BudgetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "b_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.budget"
                    ),
                ),
                (
                    "type_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.type"
                    ),
                ),
            ],
            options={"unique_together": {("b_id", "type_name")},},
        ),
        migrations.CreateModel(
            name="BudgetManage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ab_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.accountbook",
                    ),
                ),
                (
                    "b_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.budget"
                    ),
                ),
            ],
            options={"unique_together": {("b_id", "ab_id")},},
        ),
        migrations.CreateModel(
            name="ABLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ab_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.accountbook",
                    ),
                ),
                (
                    "l_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.log"
                    ),
                ),
            ],
            options={"unique_together": {("l_id", "ab_id")},},
        ),
    ]
