# Generated by Django 4.2.7 on 2023-11-24 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 24, 20, 53, 17, 878728)
            ),
        ),
    ]
